.\" Copyright (c) 2013-2014 Yubico AB
.\" See the file COPYING for license statement.
.\"
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH yhsm-daemon "1" "May 2013" "python-pyhsm"

.SH NAME
yhsm-daemon \(hy Allow multiple users of a YubiHSM.

.SH SYNOPSIS
.B yhsm\-daemon [\fIoptions\fR] [device] [port]

.SH DESCRIPTION
This is a daemon to allow multiple users of a YubiHSM without requiring
permission to use the device. The daemon listens on a TCP port on localhost
and allows multiple connections to share a YubiHSM. Access the YubiHSM via
the daemon by specifying a device string following the yhsm://<host>:<port>
syntax:

hsm = YHSM('yhsm://localhost:5348')

Note that the daemon and clients need to share the same version number to be
compatible.

.SH OPTIONS
.PP
.TP
\fB\-h\fR, \fB\-\-help\fR
Shows this help message and exit
.TP
\fB\-D\fR, \fB\-\-device\fR
YubiHSM device name
.TP
\fB\-I\fR, \fB\-\-interface\fR
Network interface to bind to
.TP
\fB\-P\fR, \fB\-\-port\fR
TCP port to bind to

.SH BUGS
Report python-pyhsm/yhsm-daemon bugs in
.URL "https://github.com/Yubico/python-pyhsm/issues/" "the issue tracker"

.SH "SEE ALSO"
The
.URL "https://developers.yubico.com/python-pyhsm/" "home page"
.PP
YubiHSMs and YubiKeys can be obtained from
.URL "http://www.yubico.com/" "Yubico" "."
